# Generated by Django 4.2.11 on 2024-05-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="sysmusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="文件名")),
                ("size", models.IntegerField(max_length=7, verbose_name="文件大小")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="音乐描述"),
                ),
                (
                    "types",
                    models.IntegerField(
                        choices=[(0, "mp3"), (1, "txt")],
                        default=0,
                        verbose_name="文件类型,0:mp3,1:txt",
                    ),
                ),
                (
                    "mold",
                    models.IntegerField(
                        choices=[(1, "net_music"), (2, "it_music"), (3, "txt_music")],
                        default=1,
                        verbose_name="音乐来源,0:net_music,1:it_music,2:txt_music",
                    ),
                ),
                (
                    "MD5",
                    models.CharField(max_length=40, unique=True, verbose_name="MD5"),
                ),
                ("url", models.URLField()),
                ("is_delete", models.BooleanField(default=False)),
                ("upload_date", models.DateField(auto_now=True, verbose_name="记录修改时间")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "pid",
                    models.IntegerField(
                        default=0, max_length=7, verbose_name="若为算法生成的文件，则记录对应的源文件id"
                    ),
                ),
                (
                    "uid",
                    models.IntegerField(
                        default=0, max_length=7, verbose_name="该文件对应的用户id"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sysuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, verbose_name="用户名")),
                ("password", models.CharField(max_length=20, verbose_name="密码")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="个性标签"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "admin"), (1, "user")],
                        default=1,
                        verbose_name="角色标签,0:admin,1:user",
                    ),
                ),
            ],
        ),
    ]
