# Generated by Django 4.2.11 on 2024-05-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangomusic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysmusic",
            name="MD5",
            field=models.CharField(max_length=40, verbose_name="MD5"),
        ),
        migrations.AlterField(
            model_name="sysmusic",
            name="pid",
            field=models.IntegerField(default=0, verbose_name="若为算法生成的文件，则记录对应的源文件id"),
        ),
        migrations.AlterField(
            model_name="sysmusic",
            name="size",
            field=models.IntegerField(verbose_name="文件大小"),
        ),
        migrations.AlterField(
            model_name="sysmusic",
            name="uid",
            field=models.IntegerField(default=0, verbose_name="该文件对应的用户id"),
        ),
        migrations.AlterField(
            model_name="sysmusic",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]