# Generated by Django 4.2.11 on 2024-05-28 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangomusic.views.basicFuction


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("djangomusic", "0002_alter_sysmusic_md5_alter_sysmusic_pid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="评论者id")),
                ("music_id", models.IntegerField(verbose_name="歌曲id")),
                ("content", models.TextField(verbose_name="评论内容")),
                ("support", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论创建时间"),
                ),
                (
                    "delete_mark",
                    models.IntegerField(
                        choices=[(0, "未删"), (1, "已删")],
                        default=0,
                        verbose_name="删除标志,0:未删,1:已删",
                    ),
                ),
                ("pid", models.IntegerField(default=0, verbose_name="父级评论id")),
            ],
        ),
        migrations.CreateModel(
            name="listMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("songList_id", models.IntegerField(verbose_name="歌单id")),
                ("music_id", models.IntegerField(verbose_name="歌曲id")),
                (
                    "delete_mark",
                    models.IntegerField(
                        choices=[(0, "未删"), (1, "已删")],
                        default=0,
                        verbose_name="删除标志,0:未删,1:已删",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="listUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户id")),
                ("songList_id", models.IntegerField(verbose_name="歌单id")),
                (
                    "delete_mark",
                    models.IntegerField(
                        choices=[(0, "未删"), (1, "已删")],
                        default=0,
                        verbose_name="删除标志,0:未删,1:已删",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="歌曲名")),
                ("singer", models.CharField(max_length=20, verbose_name="歌手")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="音乐描述"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avater", verbose_name="歌曲图片展示"
                    ),
                ),
                ("duration_time", models.TimeField(verbose_name="歌曲时长")),
                ("support", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "mold",
                    models.IntegerField(
                        choices=[(1, "网络音乐"), (2, "源音频"), (3, "AI音频")],
                        default=1,
                        verbose_name="音乐来源",
                    ),
                ),
                ("MD5", models.CharField(max_length=40, verbose_name="MD5，唯一标识")),
                ("url", models.URLField(verbose_name="音频的url地址")),
                (
                    "is_upload",
                    models.IntegerField(
                        choices=[(0, "未上传"), (1, "已上传")],
                        default=1,
                        verbose_name="上传标识，针对AI歌曲",
                    ),
                ),
                (
                    "delete_mark",
                    models.IntegerField(
                        choices=[(0, "未删"), (1, "已删")],
                        default=0,
                        verbose_name="删除标志,0:未删,1:已删",
                    ),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "upload_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="上传时间，新歌榜需针对上传时间进行排序"
                    ),
                ),
                ("pid", models.IntegerField(default=0, verbose_name="针对AI音频，记录源音频id")),
                ("uid", models.IntegerField(default=0, verbose_name="针对AI音频，记录创建用户id")),
            ],
        ),
        migrations.CreateModel(
            name="songList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="歌单名")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="歌单描述"),
                ),
                ("duration_time", models.TimeField(verbose_name="歌曲时长")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avater", verbose_name="歌单图片展示"
                    ),
                ),
                ("support", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "is_upload",
                    models.IntegerField(
                        choices=[(0, "未上传"), (1, "已上传")],
                        default=1,
                        verbose_name="上传标识，针对AI歌曲",
                    ),
                ),
                (
                    "delete_mark",
                    models.IntegerField(
                        choices=[(0, "未删"), (1, "已删")],
                        default=0,
                        verbose_name="删除标志,0:未删,1:已删",
                    ),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("upload_date", models.DateField(auto_now=True, verbose_name="上传时间")),
                ("uid", models.IntegerField(verbose_name="歌单创建用户id")),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, verbose_name="用户名")),
                ("password", models.CharField(max_length=20, verbose_name="密码")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="个性标签"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avater", verbose_name="头像"
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "admin"), (1, "user")],
                        default=1,
                        verbose_name="角色标签,0:admin,1:user",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "delete_mark",
                    models.IntegerField(
                        choices=[(0, "未删"), (1, "已删")],
                        default=0,
                        verbose_name="删除标志,0:未删,1:已删",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="userMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户id")),
                ("music_id", models.IntegerField(verbose_name="歌曲id")),
                (
                    "listen_time",
                    models.DateTimeField(auto_now=True, verbose_name="听歌时间"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="sysmusic",
        ),
        migrations.DeleteModel(
            name="sysuser",
        ),
    ]
