# Generated by Django 4.2.11 on 2024-05-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangomusic", "0003_comment_listmusic_listuser_music_songlist_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="comment",
            new_name="sysComment",
        ),
        migrations.RenameModel(
            old_name="music",
            new_name="sysMusic",
        ),
        migrations.RenameModel(
            old_name="user",
            new_name="sysUser",
        ),
    ]
