# Generated by Django 4.2.11 on 2024-06-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "djangomusic",
            "0004_rename_comment_syscomment_rename_music_sysmusic_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="auditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("songList_id", models.IntegerField(default=0, verbose_name="歌单id")),
                ("music_id", models.IntegerField(default=0, verbose_name="歌曲id")),
                ("audit_id", models.IntegerField(verbose_name="审核人id,便于查找审核记录")),
                (
                    "audit_mold",
                    models.IntegerField(
                        choices=[
                            (0, "审核未开始"),
                            (1, "歌曲审核中"),
                            (2, "歌单审核中"),
                            (3, "审核失败"),
                            (4, "审核成功，可上传"),
                        ],
                        default=0,
                        verbose_name="审核阶段",
                    ),
                ),
                ("msg_content", models.TextField(verbose_name="审核结果")),
                (
                    "delete_mark",
                    models.IntegerField(
                        choices=[(0, "未删"), (1, "已删")],
                        default=0,
                        verbose_name="删除标志,0:未删,1:已删",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="songlist",
            name="audit_id",
            field=models.IntegerField(default=0, verbose_name="上传审核id"),
        ),
        migrations.AddField(
            model_name="sysmusic",
            name="audit_id",
            field=models.IntegerField(default=0, verbose_name="上传审核id"),
        ),
        migrations.AlterField(
            model_name="songlist",
            name="is_upload",
            field=models.IntegerField(
                choices=[(0, "未上传"), (1, "审核中"), (2, "审核失败，无法上传"), (3, "审核成功，上传成功")],
                default=1,
                verbose_name="上传标识",
            ),
        ),
        migrations.AlterField(
            model_name="sysmusic",
            name="is_upload",
            field=models.IntegerField(
                choices=[(0, "未上传"), (1, "审核中"), (2, "审核失败，无法上传"), (3, "审核成功，上传成功")],
                default=1,
                verbose_name="上传标识，针对AI歌曲",
            ),
        ),
    ]
