
# Generated by Django 4.2.11 on 2024-06-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangomusic", "0005_auditlog_songlist_audit_id_sysmusic_audit_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songlist",
            name="duration_time",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="audit_state",
            field=models.IntegerField(
                choices=[
                    (0, "审核未开始"),
                    (1, "歌曲审核中"),
                    (2, "歌单审核中"),
                    (3, "审核失败"),
                    (4, "审核成功，可上传"),
                ],
                default=0,
                verbose_name="审核阶段",
            ),
        ),
        migrations.AddField(
            model_name="songlist",
            name="number",
            field=models.IntegerField(default=0, verbose_name="歌单含歌曲数量"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="audit_mold",
            field=models.IntegerField(
                choices=[(0, "music"), (1, "songList")], default=0, verbose_name="审核类型"
            ),
        ),
        migrations.AlterField(
            model_name="songlist",
            name="is_upload",
            field=models.IntegerField(
                choices=[(0, "未上传"), (1, "审核中"), (2, "审核失败，无法上传"), (3, "审核成功，上传成功")],
                default=0,
                verbose_name="上传标识",
            ),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="role",
            field=models.IntegerField(
                choices=[(0, "admin"), (1, "user"), (2, "auditor")],
                default=1,
                verbose_name="角色标签,0:admin,1:user",
            ),
        ),
    ]
