# Generated by Django 4.2.11 on 2024-06-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "djangomusic",
            "0006_remove_songlist_duration_time_auditlog_audit_state_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="audit_id",
            field=models.IntegerField(default=0, verbose_name="审核人id,便于查找审核记录"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="audit_state",
            field=models.IntegerField(
                choices=[
                    (0, "审核未开始"),
                    (1, "歌曲审核中"),
                    (2, "歌单审核中"),
                    (3, "不予上传"),
                    (4, "审核成功，可上传"),
                ],
                default=0,
                verbose_name="审核阶段",
            ),
        ),
    ]