# Generated by Django 4.2.11 on 2024-06-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangomusic", "0007_alter_auditlog_audit_id_alter_auditlog_audit_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sysmusic",
            name="duration_time",
        ),
        migrations.AddField(
            model_name="sysmusic",
            name="duration_seconds",
            field=models.IntegerField(default=0, verbose_name="歌曲时长（秒）"),
        ),
    ]