# Generated by Django 4.2.11 on 2024-06-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangomusic", "0008_remove_sysmusic_duration_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songlist",
            name="upload_date",
            field=models.DateField(blank=True, null=True, verbose_name="上传时间"),
        ),
        migrations.AlterField(
            model_name="sysmusic",
            name="upload_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="上传时间，新歌榜需针对上传时间进行排序"
            ),
        ),
    ]